# Generated by Django 4.1.5 on 2023-03-06 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evenement'},
        ),
        migrations.AlterModelOptions(
            name='event_participation',
            options={'verbose_name': 'Person'},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='Date doit etre sup à date sys',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 3, 6, 11, 7, 40, 173886))), name='Date doit etre sup à date sys'),
        ),
    ]
